# Configuration INSEE Data Processor
# Utilisé pour personnaliser le comportement du module selon vos besoins

# Configuration API INSEE
api:
  base_url: "https://api.insee.fr/api-sirene/3.11"
  # Délai entre requêtes (secondes) - respecter limite 30req/min
  delay_between_requests: 4.0
  # Nombre maximum de résultats par recherche
  max_results: 5
  # Timeout pour les requêtes HTTP (secondes)
  timeout: 30

# Configuration du cache
cache:
  # Activer le cache pour éviter requêtes dupliquées
  enabled: true
  # Taille maximale du cache (nombre d'entreprises)
  max_size: 10000

# Configuration traitement des doublons
duplicates:
  # Analyser et optimiser les doublons
  analyze: true
  # Afficher les statistiques détaillées
  show_stats: true
  # Nombre d'exemples de doublons à afficher
  top_duplicates_display: 10

# Configuration Salesforce
salesforce:
  # Correction automatique des effectifs manquants
  auto_fix_missing: true
  
  # Mapping des tailles d'entreprise vers effectifs par défaut (seuils INSEE officiels)
  size_mapping:
    MICRO:
      default_employees: 10        # Milieu de 0-19
      min_threshold: 0
      max_threshold: 19
      description: "0 à 19 salariés"
      confidence: "medium"
    PME:
      default_employees: 135       # Milieu de 20-249
      min_threshold: 20
      max_threshold: 249
      description: "20 à 249 salariés"
      confidence: "medium"
    ETI:
      default_employees: 2625      # Milieu de 250-4999
      min_threshold: 250
      max_threshold: 4999
      description: "250 à 4999 salariés"
      confidence: "medium"
    GE:
      default_employees: 10000     # Estimation pour 5000+
      min_threshold: 5000
      max_threshold: 999999
      description: "5000 salariés et plus"
      confidence: "low"
  
  # Niveaux de confiance selon la taille des tranches
  confidence_levels:
    # Tranches précises (1-50 employés)
    high_threshold: 50
    # Tranches moyennes (50-1000 employés)
    medium_threshold: 1000
    # Grandes tranches (>1000 employés) = confiance faible

# Configuration des colonnes d'entrée par défaut
default_columns:
  # Nom de colonne par défaut pour les entreprises
  company: "Organisation"
  # Nom de colonne par défaut pour la taille
  size: "Taille"

# Configuration des fichiers de sortie
output:
  # Répertoire de sortie par défaut
  directory: "output"
  # Préfixe pour les fichiers générés
  prefix: "enriched"
  # Suffixe pour les fichiers corrigés
  corrected_suffix: "_refactor"
  # Encodage des fichiers CSV
  encoding: "utf-8"

# Configuration du logging
logging:
  # Niveau de logging (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  # Format des logs
  format: "%(levelname)s - %(message)s"
  # Afficher la progression tous les N éléments
  progress_frequency: 10

# Configuration mode démo
demo:
  # Limite par défaut pour le mode démo
  default_limit: 50
  # Préfixe pour les fichiers démo
  prefix: "demo"